### ISSUE TITLE
setBadge

### ISSUE THREAD

**Issue by jcsomac** [caffeinalab/gcm#1]
i am using the GSM module, and i have this error:

<code>
[ERROR] :  TiExceptionHandler: (main) [139,1047] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,1047] - In app.js:100,36
[ERROR] :  TiExceptionHandler: (main) [0,1047] - Message: Uncaught TypeError: Object #<CaffeinaGCM> has no method 'setBadge'
[ERROR] :  TiExceptionHandler: (main) [0,1047] - Source:         require('it.caffeina.gcm').setBadge(2);
[ERROR] :  V8Exception: Exception occurred at app.js:100: Uncaught TypeError: Object #<CaffeinaGCM> has no method 'setBadge'
</code>

I am using the version 1.3.0 of Caffeine/GSM with 
Appcelerator Studio 4.3.0.201509151348
SDK: 5.0.0.GA

Regards

**Comment by kopiro** [comment]
Sorry, maybe it's my fault: the method is `setAppBadge`, not `setBadge`.
Let me know.

**Comment by jcsomac** [comment]
Now its ok, but there are no number in the right-top corner ....

**Comment by kopiro** [comment]
Did you actually set a number via `setAppBadge(N>0)` ?

**Comment by jcsomac** [comment]
Yeap... it was:  ......setAppBadge(3);
do you want me to do some specific test ?

**Comment by jcsomac** [comment]
look, when i use "badge" in the JSON i get this:

![Screenshot](http://187.188.107.45:8095/temporal/IMG_6837.jpg)

the JSON is:

```
  $json = '{
    "registration_ids": ["token"],
    "data": {
      "data":{
        "alert":  "Esto es una prueba",
        "title":  "MiAsistencia",
        "sound": "default",
        "priority": 2,
        "vibrate": true,
        "badge": 3,
        "cveexped":  999,
        "tipo_push":  1
      }
    }
  }';
```

The badge number is show in the notifications list... but not in the right-top corner of the app icon.

Thanks in advance.

**Comment by kopiro** [comment]
Ok, i got it.

Due system limitations, currently the badge over the icon is supported only on Samsung and Sony devices.
This is why there's no an "Android official method" to draw that badge, but only via private API.

Who is the retailer of your smartphone?

**Comment by jcsomac** [comment]
My Smarthphone es Motorola

**Comment by kopiro** [comment]
And now it's all clear :)
I'm sorry, but we just added the most popular retailer due inconsistent APIs.

Maybe you can add an issue to support Motorola badges (if exposed by Motorola) and in the next version we add it.
