### ISSUE TITLE
Only single notification is visible even if multiple notifications are send from server

### ISSUE THREAD

**Issue by rohanpujaris** [caffeinalab/gcm#4]
Hello,

First of all thanks for the awesome module. I am having following issue with this module.
When I send multiple notification from the server only single notification is visible in notification area. Lats notification replaces the previous notification. Is it possible to show multiple notification using this module or this feature is not build in this module.

**Comment by rohanpujaris** [comment]
I don't know andriod and java, but i checked through the code and found this.
`((NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE)).notify(1, builder.build());`

I think its not made to work with multiple notification. notify function explanation link http://bit.ly/1YVJJJY
Is this repository maintained and will this feature be added to this module?

**Comment by kopiro** [comment]
Yes, this repo is maintained!
We'll investigate about, thanks!

**Comment by rohanpujaris** [comment]
Thanks @kopiro for the reply

**Comment by artanisdesign** [comment]
Have a look at my version [https://github.com/artanisdesign/gcm](https://github.com/artanisdesign/gcm), added support for multiple notification. More features might come.  sent a PR too, let me know if any issues.

**Comment by kopiro** [comment]
Closed!
THanks to @artanisdesign !
