### ISSUE TITLE
GCM push message layout

### ISSUE THREAD

**Issue by jeffkanazi** [caffeinalab/gcm#8]
Hi, 

Great work!  Thank you!

There appear to bit of inconsistency problem - the expected message layout is not consistent with GCM specs. The module would work fine with the following message layout: 

```
$json = '{
  "registration_ids": ["DEVICETOKEN1", "DEVICETOKEN2"],
  "data": {
    "data":{
      "alert":"ALERT",
      "title": "My awesome app",
      "sound": "default",
      "priority": 2,
      "vibrate": true
    }
  }
}';

```

but according to Google it should really work with this instead: 

```
$json = '{
  "registration_ids": ["DEVICETOKEN1", "DEVICETOKEN2"],
    "data":{
      "alert":"ALERT",
      "title": "My awesome app",
      "sound": "default",
      "priority": 2,
      "vibrate": true
    }
}';
```

As a result the module is not receiving push notifications when those are sent with any of the popular gcm jars out there including this one: [https://github.com/google/gcm](https://github.com/google/gcm). 

In a way this is OK as long as the push messages from the app server are in the expected format, however, if one needed to send push notifications to different apps from the same server it would have been a lot simpler if all of them could use the same layout as per [https://developers.google.com/cloud-messaging/http](https://developers.google.com/cloud-messaging/http). 

Should be a simple thing to change. I would not mind doing it too.

**Comment by kopiro** [comment]
Yes, you're right, but...

We used this format because it's Parse (parse.com) compatible, and then with this change we can send the push notification directly from the backend.

Maybe we can change the format when Parse will be dismissed or in a new major release! :)

**Comment by kopiro** [comment]
@jeffkanazi https://github.com/caffeinalab/ti.goosh
